"""empty message

Revision ID: 34535ce3d04c
Revises: f3de25ea9ca7
Create Date: 2020-12-20 01:17:34.443286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34535ce3d04c'
down_revision = 'f3de25ea9ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('todolist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todolists', ['todolist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'todolist_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
