"""empty message

Revision ID: 919f0b495b58
Revises: f2959bde37a3
Create Date: 2020-12-20 17:27:23.202622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919f0b495b58'
down_revision = 'f2959bde37a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
