"""empty message

Revision ID: 553657dafa67
Revises: 7e892c998f47
Create Date: 2020-12-26 14:17:24.420893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553657dafa67'
down_revision = '7e892c998f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
